### PR TITLE
Add CALE instructions and citation to README

### PR DESCRIPTION
**Pull request by psc-g**
Adding instructions for how to use CALE (Continuous ALE), as well as citation instructions.

Will also add instructions to https://ale.farama.org/environments/.

### CODE REVIEW

**Review by pseudo-rnd-thoughts — APPROVED** [review]
Thanks Pablo, that looks great

**Comment by psc-g** [comment]
Thanks for the quick review, Mark!

It seems the changes are not yet reflected on the gymnasium atari page (https://ale.farama.org/environments/). Is there a manual step that needs to run, or will this eventually be automatically picked up?

**Comment by pseudo-rnd-thoughts** [comment]
The website is version controlled, so it does exist for main, https://ale.farama.org/main/environments/#continuous-action-space
I will see if we can make a manual version control to update the website

**Comment by psc-g** [comment]
ah perfect, thanks!

**Pull request merged**
